export const ROOT_DIR = process.env.ROOT_DIR || './'
export const STREAMS_DIR = process.env.STREAMS_DIR || './streams'
export const PUBLIC_DIR = process.env.PUBLIC_DIR || './.gh-pages'
export const README_DIR = process.env.README_DIR || './.readme'
export const API_DIR = process.env.API_DIR || './.api'
export const DATA_DIR = process.env.DATA_DIR || './temp/data'
export const LOGS_DIR = process.env.LOGS_DIR || './temp/logs'
export const API_URL = process.env.API_URL || 'https://paulysid.github.io/api'
export const TESTING = process.env.NODE_ENV === 'test' ? true : false
export const OWNER = 'paulysid'
export const REPO = 'mediaStream'
export const EOL = '\r\n'
